# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:year/:month/:title.html
relative_permalinks: false

# Setup
title:               Flavours of a Nerd
tagline:             'Human and Machine Learning'
description:         "FoaN is a space dedicated for simple experiments and insights. I occasionally give useful tutorials and my personal opinions on life and stuff."
url:                 http://sizhky.github.io/
baseurl:             
paginate:            3
show_drafts:         false
# About/contact
author:
  name:              Yeshwanth
  url:               https://twitter.com/sizhky
  email:             1992chinna@gmail.com
excerpt_separator: <!--more-->
# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
# Conversion
markdown:    kramdown
highlighter: rouge

#Comments
comments: true
