# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:year/:month/:title.html
relative_permalinks: false

# Setup
title:               Ignosi Labs
tagline:             'Human and Machine Learning'
description:         "This is a space dedicated for experiments and insights. I occasionally give useful tutorials."
url:                 http://sizhky.github.io/
baseurl:
paginate:            4
show_drafts:         false
# About/contact
author:
  name:              Yeshwanth
  url:               https://twitter.com/sizhky
  email:             1992chinna@gmail.com
excerpt_separator: <!--more-->
# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
plugins: [jekyll-paginate]
# Conversion
markdown:    kramdown
highlighter: rouge

#Comments
comments: true
